platform :ios, '13.0'

# Required by Flutter
use_frameworks!
flutter_application_path = '../'

# Enable Fluter plugins
plugin 'flutter_plugin'

# Add custom settings here if needed

target 'Runner' do
  use_frameworks!

  # Flutter dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Add any other dependencies you need for Firebase or other plugins

  # This is required to build Flutter dependencies
  flutter_install_all_ios_pods(flutter_application_path)
end
